### ISSUE TITLE
Website contributor practice

### ISSUE THREAD

**Issue by mccarthy-m-g** [Open-Science-Student-Support-Group/osssg-website#19]
If you plan to contribute to the website could you please leave a comment below.

Once you do I’ll assign you an issue with instructions on your practice assignment. You can use that issue to provide feedback on your experience.

Members participating:

- [x] Gwen

**Comment by TinyTechieT** [comment]
hi! 
I would like to contribute to the website.

**Comment by GwenvdW** [comment]
Hey! I assume the task here is to try out the 'New Post Workflow' tutorial on adding posts to the website? 

I made a start, but got stuck on the code we're supposed to run in R Studio - when I open de project file (osssg-website.Rproj) and try to run 'quarto preview', it gives me this error:

Error: unexpected symbol in "quarto preview"

I don't think R Studio knows what quarto is yet, so I'm wondering if there is a step missing in the tutorial to integrate/activate quarto in R Studio?

**Comment by mccarthy-m-g** [comment]
Hey! Oops, sorry, I forgot to assign you a task! Yes, that's what I was going to ask you to do 😄 If you could edit the descriptions for the event posts that have placeholder descriptions right now that would be good. You can also add some of the missing events from 2022 if you want.

## RStudio + Quarto

RStudio does know what Quarto is, although if you're using an older version it might not. Version `2021.09.2` or later should be good.

The error you're getting is because you're running `quarto preview` in the R console, which is for R code only. The `quarto preview` command is for the command line, so you need to run it in the Terminal pane in RStudio:

![Screen Shot 2022-07-19 at 2 49 40 PM](https://user-images.githubusercontent.com/51542091/179846000-a7888098-072a-4469-b0c3-1f26107d56db.png)

I think I specified that in the tutorial, but if you think I could make it clearer feel free to submit a PR for an edit on that part.

**Comment by GwenvdW** [comment]
Okay yeah my RStudio was too old (no terminal to be found), but also my older Mac work computer is apparently too old to work with Quarto.. So I tried again on my laptop, and I ran into this issue that from the moment I run 'quarto preview' in the terminal, it changes a bunch of the files in the directory and gives an error... 

![image](https://user-images.githubusercontent.com/66083270/180084388-a6ca1ade-2d65-490b-93ed-9fec8da553a7.png)

**Comment by mccarthy-m-g** [comment]
Oh your Mac must be really old then!

It's okay that it changed a bunch of files in the `_site` directory, so don't worry about that.

I think the error is caused by line 84 in `documents/posts/new-post-workflow/index.md`:

```
Install [GitHub Desktop]((https://desktop.github.com))
```

I accidentally made a typo with the link there (the double-parentheses), which apparently Windows doesn't like since it seems to be interpreting it as a file path instead of a URL. Try changing the line to this:

```
Install [GitHub Desktop](https://desktop.github.com)
```

Then see if `quarto preview` works.

**Comment by GwenvdW** [comment]
uhm well if you consider 2017 to be very old, I guess...

Anyway, the quarto preview bit works with that edit to the code (would be good to change in the main version too, as I imagine others may be using windows too). I don't really have energy to go through the rest of it anymore though, so here's my feedback based on the first bit:

I like the set-up and structure of the tutorial, especially the windows for the different types of software. On first read the instructions seem clear and concise, though they may need some expansion here and there to help people actually complete the steps even if they are not familiar with the softwares yet. Downloading and setting up the softwares is a bit much if you don't have any of it yet, but I guess that is just the way it is. Some things I think would be good to add/change:

* Explicitly mention that you need to switch from the console to the terminal window before entering code 
* Specify the requirements in terms of version of software that is needed (e.g., RStudio, OS)
* Add instructions on installing R (RStudio wouldn't open for me without installing R)
* In the renaming warning (under Create a new post), I think the format should say 'date' instead of 'data'? If so, this needs to be changed for both templates
* At the start of the 'Create a new post' section, I would specify that people should switch to their own folder system (so people don't start trying to do stuff through GitHub Desktop)
* For point 3., I would specify where folx can open the markdown files (I think any text editor?)

I think it would be great if some more folx could run through the whole thing and give feedback on the later part as well, but generally looks like a great start!

**Comment by mccarthy-m-g** [comment]
Oh weird. My Mac is from 2013 and works with Quarto. Maybe your OS needs updating? Mine is on Mojave, so that or later should work.

Thanks for the feedback! Appreciate it! I made those changes; you can them here <https://github.com/Open-Science-Student-Support-Group/osssg-website/pull/26/commits/80013d7d786595f53135fc8fbe74060565a6805d#diff-9222f818d925b99d58d6f24851f59b2bae2b6376b22c283bef2223798e93f1e8> and see the site preview here <https://deploy-preview-26--osssg.netlify.app/documents/posts/new-post-workflow/>
